# Generated by Django 4.2.7 on 2023-11-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_img_product_image'),
    ]

