# Generated by Django 4.2.7 on 2023-11-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_img_product_image'),
    ]
